# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("=" * 74)
print("回答你的问题: 是写死的, 还是真透传?")
print("=" * 74)
print()
print("答: 【真透传】。右板通过 USB Host 真实读取你的键盘, 没有任何写死的数据。")
print()
print("证据链 (逐行核对过源码):")
print()
print("  右板 esp_usb_host.cpp:1026")
print("      kbdHostOnRawReport(transfer->data_buffer, transfer->actual_num_bytes);")
print("                                                     ^^^^^^^^^^^^^^^^^^")
print("      这是 USB 主机端点【实际收到的字节】, 不是我编的")
print()
print("  右板 main.cpp: kbdHostOnRawReport()")
print("      只做长度检查 + 打包, 直接 sendToLeft(data, len)")
print("      没有 switch/查表/映射 —— 不可能写死")
print()
print("  左板 usb_hid.cpp: kbdUsbSendReport()")
print("      唯一动作: 在最前面补一个 Report ID 字节")
print("      memcpy(&buf[1], payload, len)  <- 你键盘的字节原样跟在后面")
print()
print("  关键: 固件里【没有任何】键码表、扫描码映射、厂商 ID 判断。")
print()
print("=" * 74)
print("透传了什么 / 没透传什么")
print("=" * 74)
print()
print("  透传 (原样复制):")
print("    [OK] 报告内容 —— modifier + reserved + 6 个键码, 一个 bit 都不改")
print("    [OK] 报文长度")
print("    [OK] 报文先后顺序 (按 USB 主机收到的次序)")
print("    [OK] 全零报文 (所有键松开) —— 这个必须发, 否则会一直以为按着")
print("    [OK] 多媒体键 / 组合键 / 厂商自定义键 (因为不解析, 天然保留)")
print()
print("  没透传 (有意为之):")
print("    [--] 轮询间隔 / 刷新率 —— 左板自己用 1ms")
print("    [--] 键盘 LED 状态 (Caps/Num/Scroll 指示灯) —— 见下方说明")
print("    [--] 设备身份 (VID/PID/序列号) —— 左板用固定值 3554:FA09")
print()
print("=" * 74)
print("唯一需要你注意的一点: 键盘 LED")
print("=" * 74)
print()
print("  被控机设置 Caps Lock 时, 会通过 SET_REPORT 下发 LED 状态。")
print("  当前左板的 tud_hid_set_report_cb 是空的 —— 收到了但不处理,")
print("  也没有回传给右板, 所以【真键盘上的 Caps Lock 灯不会亮】。")
print()
print("  功能本身没问题: Caps Lock 打字依然是大写, 只是真键盘的灯不跟着变。")
print("  如果你需要这个灯, 我可以加一条反向通道 (左板 -> 右板 -> 真键盘)。")
print()
print("  另外: 左板给被控机报的是固定序列号 000000000001,")
print("        所以插哪个键盘, 被控机看到的都是同一个设备。")
