# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("=" * 78)
print("你的最终需求的完整拆解")
print("=" * 78)
print()
print("  硬件: 两个马克")
print("    键盘马克: USB-C 插真键盘")
print("    鼠标马克: USB-C 插真鼠标")
print()
print("  每个马克都要做两件事:")
print("    1) 透传真实设备 (键盘马克透传键, 鼠标马克透传鼠标)")
print("    2) 接受上位机注入 (经 CH343)")
print()
print("  注入内容:")
print("    鼠标马克 <- 移动 + 按键")
print("    键盘马克 <- 按键")
print()
print("  特殊需求:")
print("    键盘马克要能【短暂屏蔽真实键盘】(屏蔽期间上位机也不注入)")
print()
print("=" * 78)
print("关键问题: 一套固件 还是 两套?")
print("=" * 78)
print()
print("  ★ 答案: 【一套固件】。理由:")
print()
print("  1) 两块马克的【硬件完全一样】(同一块 PCB)")
print("  2) 两块马克的【角色差异】只在 USB-C 那头插的是什么")
print("  3) 左板(Device)需要暴露的接口形状, 可以按【插了什么】自动决定")
print()
print("  也就是说: 固件开机后检测 USB-C 插入设备的类型,")
print("            自动切换到'键盘模式'或'鼠标模式'。")
print()
print("  这正好复用现有代码里已经有的判定逻辑:")
print("      iface_isKbd[]  / iface_isMouse[]   (右板按接口标记)")
print()
print("=" * 78)
print("但有一个必须现在就定的架构问题: 左板要暴露什么形状")
print("=" * 78)
print()
print("  方案甲: 左板永远暴露【键盘+鼠标两个 Collection】(现在的做法)")
print("     优点: 一套描述符, 简单")
print("     缺点: 鼠标马克上, 被控机会看到一个从来不用的键盘 Collection")
print("           某些反作弊/游戏可能觉得可疑")
print()
print("  方案乙: 左板按插了什么, 【只暴露对应那一个】Collection")
print("     键盘马克 -> 只有键盘 Collection")
print("     鼠标马克 -> 只有鼠标 Collection")
print("     优点: 形状最干净, 与真设备最像(真鼠标就是纯鼠标设备)")
print("     缺点: 描述符要准备两份, 且要在枚举前决定")
print()
print("  方案丙: 保留现有双 Collection, 但用不上的一边从不发报文")
print("     (折中, 但其实是方案甲的退化)")
print()
print("  ★ 我倾向【方案乙】。因为:")
print("     - 你说过担心'vid对不上被封', 说明你在意被控机侧的观感")
print("     - 真鼠标 = 纯鼠标设备, 真键盘 = 纯键盘(或键鼠一体接收器)")
print("     - 方案乙与真实形状最接近")
print()
print("     而且实现代价很小: 描述符本来就是我可以完全控制的,")
print("     只要在枚举前根据检测结果选一份描述符即可。")
print()
print("=" * 78)
print("第二个架构问题: CH343 注入的数据从哪块板进?")
print("=" * 78)
print()
print("  你说: '中间的ch343口也能够让上位机注入'")
print()
print("  ★ 需要你确认: CH343 是接在【左板】还是【右板】?")
print()
print("  情况A: CH343 接左板 (Serial)")
print("     -> 上位机直接跟左板说话, 左板自己合并'真实+注入'")
print("     -> 延迟最低 (少一跳)")
print()
print("  情况B: CH343 接右板 (Serial)")
print("     -> 右板合并后经 Serial1 发左板")
print("     -> 多一跳, 但右板本来就在处理真实设备流")
print()
print("  从你之前测试看, CH343 是接在【左板】的")
print("  (因为插上后我读到的是 [KBD-DEV] 开头的日志)")
print()
print("  如果确实接左板, 那架构是:")
print()
print("      真键盘 --> 右板 --> Serial1 --> 左板 --+")
print("                                            |")
print("      上位机 ---------> CH343 ----> 左板 ----+--> 合并 --> USB --> 被控机")
print()
print("  这个架构好: 合并逻辑只在左板一处, 简单且低延迟。")
