# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("=" * 74)
print("硬约束: 预编译 TinyUSB 只支持 1 个 HID 实例")
print("=" * 74)
print()
print("证据链:")
print("  1) 工程里没有 TinyUSB 的 .c 源码 (只有 88 个头文件)")
print("     -> 实现全部来自预编译的 libarduino_tinyusb.a")
print()
print("  2) 该库的 sdkconfig: CONFIG_TINYUSB_HID_ENABLED = 1")
print("     而 tusb_config.h: #define CFG_TUD_HID CONFIG_TINYUSB_HID_ENABLED")
print("     -> 库编译时 CFG_TUD_HID = 1")
print()
print("  3) 符号验证: _hidd_itf 总大小 = 0x8c = 140 字节")
print("     tud_hid_n_report 里 instance 步长 = 140 字节")
print("     -> 数组只放得下 1 个实例")
print()
print("  4) 工程里写 -DCFG_TUD_HID=2 无效")
print("     -> 那只影响本工程编译的代码, 改不了已编译好的 .a")
print()
print("=" * 74)
print("这对方案意味着什么")
print("=" * 74)
print()
print("  × 不能注册【两个 HID 接口】(键盘 + 鼠标各占一个 instance)")
print("    TinyUSB 的 hidd_open() 对第二个 HID 接口会失败")
print()
print("  √ 但可以注册【一个 HID 接口, 内含两个 Top-Level Collection】")
print("    一个接口 = 一个 instance, 这是 TinyUSB 支持的")
print()
print("=" * 74)
print("重新设计: 单接口 + 双 Collection + Report ID 区分")
print("=" * 74)
print()
print("  接口 0: Class_03 / SubClass_01 / Prot_01  (Boot Keyboard)")
print("    报告描述符:")
print("      Report ID 1 -> 键盘 (modifier + reserved + 6 keycode)")
print("      Report ID 2 -> 鼠标 (buttons + x + y + wheel)")
print()
print("  为什么一个接口里放两个 Collection 就够:")
print("    * Windows 的 HID 类驱动会遍历接口内的所有 Top-Level Collection")
print("    * 每个含 Usage Page 0x01/Usage 0x06 的 Collection 都会被 kbdhid 接管")
print("    * kbdhid / mouhid 是【按 Collection】加载的, 不是按接口")
print("    * 所以单接口多 Collection 的键盘是能被系统识别的")
print()
print("  与真键盘接收器的差异:")
print("    真设备: 2 个接口 (MI_00 键盘, MI_01 鼠标/扩展)")
print("    本方案: 1 个接口, 2 个 Collection")
print("    对【键盘功能】而言两者等效 —— 系统都是从键盘 Collection 取键码")
