# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("=" * 74)
print("已确认: 左板完全正常")
print("=" * 74)
print()
print("  USB\\VID_3554&PID_FA09\\000000000001   ProblemCode = 0")
print("      +-- COL01 -> Keyboard")
print("      +-- COL02 -> Mouse")
print()
print("  => 描述符、报告描述符、枚举 全部正确。左板可定稿。")
print()
print("=" * 74)
print("问题在右板: 真键盘的字节没送过来")
print("=" * 74)
print()
print("我怀疑的次序 (按可能性):")
print()
print("  1) ★ 右板的 USB Host 可能根本没启动")
print("     我把 ARDUINO_USB_CDC_ON_BOOT 设成了 0, 这对【Host】模式")
print("     可能有害 —— USB Host 需要 USB 外设以 Host 模式初始化,")
print("     而我为了左板的 Device 模式把 USB 栈关掉了, 两边用了同一套宏。")
print()
print("  2) Serial1 引脚/波特率不匹配")
print("     左板: Serial1.begin(5000000, 8N1, RX=1, TX=2)")
print("     右板: Serial1.begin(5000000, 8N1, RX=2, TX=1)")
print("     这两个是交叉的, 与老工程一致 —— 应该没问题")
print()
print("  3) 钩子注入点没被执行")
print("     _onReceive 里我插在 `bool has_data = ...` 之后。")
print("     但如果这个函数在设备配置阶段就被调用而我插的位置")
print("     在某个 early-return 之后, 就永远不会执行。")
print()
print("=" * 74)
print("最可疑的是 #1")
print("=" * 74)
print()
print("  左板需要: USB Device 模式 -> 我们自己用 TinyUSB 枚举")
print("  右板需要: USB Host   模式 -> 由 esp_usb_host 驱动")
print()
print("  我给【两个工程都】加了 -DARDUINO_USB_CDC_ON_BOOT=0。")
print("  对左板这是必需的; 对右板可能是错的 ——")
print("  老右板工程【没有】这个宏, 它能正常工作。")
print()
print("  这是我引入的回归: 为了修左板, 顺手改坏了右板的配置。")
