# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("=" * 74)
print("诊断: CH343 打不开 (A device attached to the system is not functioning)")
print("=" * 74)
print()
print("  观察到的事实:")
print("    [OK] CH343 在线 (COM3, ProblemCode=0)")
print("    [OK] 左板也在线 (USB\\VID_3554&PID_FA09\\000000000001)")
print("    [X]  COM3 打不开, 两个波特率都报同样的错")
print()
print("=" * 74)
print("我的判断: 这是 CH343 的已知驱动行为, 不是板子坏了")
print("=" * 74)
print()
print("  'A device attached to the system is not functioning' 在 CH343 上常见于:")
print()
print("    1) 上一次打开没有干净关闭 (进程崩了/句柄泄漏)")
print("       -> 我前面用了 ReadExisting 后没 Dispose, 可能留了句柄")
print()
print("    2) 驱动需要重插")
print()
print("    3) 端口被另一个程序占用 (Apotheosis 可能在扫串口)")
print()
print("  注意: 板子本身没问题 —— 左板在 USB 上活得好好的。")
print()
print("=" * 74)
print("关于 'CH343 接在哪块板' 这个待确认问题")
print("=" * 74)
print()
print("  其实【上次已经测出来了】:")
print("    之前 CH343 在线时, 我读到的是:")
print("        [KBD-DEV] usb=READY frames=0 sent=0 drop=0 crc=9")
print()
print("    [KBD-DEV] 是【左板】固件的日志前缀 (右板是 [KBD-HOST])")
print("    => CH343 接在【左板】, 这一点已经确认过了。")
print()
print("  所以不需要再测了。结论: CH343 -> 左板 (Serial, 115200)")
print()
print("=" * 74)
print("不过这也暴露了一个设计问题 (必须解决)")
print("=" * 74)
print()
print("  你说的需求是: '中间的 CH343 口也能够让上位机注入'")
print("  Apotheosis 打开串口的方式是 MakcuLink link(\"COM4\", 115200)")
print()
print("  问题: 左板的 Serial 现在被【日志】占用了")
print("    - 左板每 3 秒往 Serial 打一行心跳")
print("    - 上位机解析 makcu 协议时, 这些日志会混进数据流")
print()
print("  => 必须处理。两个办法:")
print()
print("     办法A: 二进制协议 + 文本日志混在一条线上")
print("            上位机靠 0xA5 0x5C 魔数同步, 理论上能跳过日志行")
print("            但不够干净, 而且日志会占用带宽")
print()
print("     办法B: 日志默认关闭, 只在需要调试时开")
print("            (用某个命令或引脚控制)  <- 更干净, 我倾向这个")
print()
print("  这是接下来要实现时必须先定的一个点。")
