# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("=" * 74)
print("排除: 右板配置不是问题")
print("=" * 74)
print()
print("main.cpp 里所有 CDC_ON_BOOT 的用法都带 !ARDUINO_USB_MODE 守卫:")
print("  #if ARDUINO_USB_CDC_ON_BOOT && !ARDUINO_USB_MODE")
print("      Serial.begin();")
print("  #endif")
print()
print("而 MAKCM.json 里 ARDUINO_USB_MODE=1 (TinyUSB 模式),")
print("所以 !ARDUINO_USB_MODE == false -> 整段被跳过。")
print()
print("=> CDC_ON_BOOT=0 对右板【没有任何影响】。我的怀疑不成立。")
print()
print("=" * 74)
print("那么真正的原因是什么")
print("=" * 74)
print()
print("回到已知事实:")
print("  * 老右板固件 (修复9) 能让鼠标工作 -> 说明它的 USB Host 通路是好的")
print("  * 新右板固件和它共用同一份 esp_usb_host.cpp, 只多了一个钩子")
print("  * 左板已被系统正常识别为键盘")
print()
print("我在 _onReceive 里插钩子的位置:")
print()
print("    uint8_t endpoint_num = transfer->bEndpointAddress & 0x0F;")
print("    bool has_data = (transfer->actual_num_bytes > 0);")
print("    >>> if (has_data) kbdHostOnRawReport(...)   <<< 我插在这里")
print()
print("关键问题: 这个位置【对不对】?")
print("  _onReceive 是老固件里处理端点数据的函数, 老固件在这里解析鼠标/键盘。")
print("  我的钩子【在那段解析之前】, 所以应该会先收到原始字节。")
print()
print("那为什么没效果? 三种可能:")
print()
print("  A) 右板确实在执行钩子, 但 Serial1 发不出去")
print("     -> 波特率 5Mbps 在杜邦线/焊接上可能不稳")
print()
print("  B) 左板的接收解析有 bug, 把帧丢了")
print("     -> 我写了一个手写的状态机, 可能有同步问题")
print()
print("  C) 右板的 USB Host 根本没收到数据")
print("     -> 但这与老固件能收鼠标矛盾")
print()
print("=" * 74)
print("最快的确诊方式: 加一个只依赖 USB-A 的自测")
print("=" * 74)
print()
print("  让【左板】自己产生一个可控的测试报文:")
print("  开机后每隔 2 秒发一次 'A' 键的按下/释放。")
print()
print("  这样不需要右板、不需要真键盘、不需要 CH343:")
print("    * 若被控机能打出 A -> 左板 USB 通路完全 OK (已确认)")
print("    * 若打不出     -> 左板的问题")
print()
print("  但左板已经被系统认成键盘(COL01=Keyboard), 所以这一步大概率 OK。")
print()
print("  真正的未知量是【右板 -> 左板的串口链路】。")
print("  要验证它, 需要一个能在视觉上区分的数据源。")
