# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("=" * 78)
print("这三项的可行性完全不同 —— 分开看")
print("=" * 78)
print()
print("  项                    能不能透传      原因")
print("  --------------------  --------------  --------------------------------")
print("  1. 轮询间隔            【能, 且右板    右板已经读到 bInterval 了")
print("                          已经读到了】")
print("  2. 键盘 LED            【能, 要做反向   被控机->左板->右板->真键盘")
print("                          通道】")
print("  3. VID/PID/序列号      【能改, 但要看  这是左板的【固定声明】,")
print("                          你要什么】      不是实时数据")
print()
print("=" * 78)
print("1) 轮询间隔 —— 能透传, 我之前说错了")
print("=" * 78)
print()
print("  右板 esp_usb_host.cpp:383 已经在读真键盘的端点间隔:")
print("      endpoint_descriptors[endpointCounter].bInterval = ep_desc->bInterval;")
print()
print("  它只是【读了但没用】。要透传, 只需:")
print("      a) 右板把 bInterval 随帧发给左板 (协议加 1 字节)")
print("      b) 左板在描述符里用它")
print()
print("  但有个硬限制: USB 描述符里 bInterval 是【编译期写进配置描述符的】,")
print("  运行时改不了 —— 除非重新枚举(断开重连)。")
print()
print("  所以真要透传, 只能在开机握手后【用真键盘的间隔重新枚举一次】:")
print("      左板开机 -> 先用默认1ms枚举 -> 收到右板的bInterval ->")
print("      若不同则软重连并更新描述符 -> 第二次枚举用真值")
print()
print("  代价: 每次上电多一次枚举(约1秒), 且实现复杂度明显上升。")
print("  收益: 被控机看到的轮询率与真键盘一致。")
print()
print("  ★ 我的建议: 先别做。1ms 已经比多数键盘快(常见 8ms/10ms),")
print("    实际打字/游戏中【不会有可感知差异】, 但复杂度不小。")
print("    如果你有明确需求(比如某个游戏检测轮询率), 我再做。")
print()
print("=" * 78)
print("2) 键盘 LED —— 能做, 需要加一条反向通道")
print("=" * 78)
print()
print("  方向是反的:")
print("      被控机 --SET_REPORT(LED)--> 左板 --Serial1--> 右板 --控制传输--> 真键盘")
print()
print("  要做三件事:")
print("      a) 左板 tud_hid_set_report_cb 里把 LED 字节存下来")
print("      b) 通过 Serial1 反向发一个 LED 帧(新帧类型 0x24)")
print("      c) 右板收到后, 对真键盘发起 SET_REPORT 控制传输")
print()
print("  难度: 中等。(c) 稍微麻烦 —— 要对【键盘接口】的端点发控制请求,")
print("        需要正确构造 usb_host_transfer、wValue/wIndex 等。")
print()
print("  收益: Caps/Num/Scroll 灯跟着亮, 更接近真键盘行为。")
print()
print("      注意: 很多反作弊/游戏环境【不看】LED 状态,")
print("            所以这个主要是手感一致性问题, 不是功能问题。")
print()
print("=" * 78)
print("3) VID/PID/序列号 —— 现在就是固定的, 可以改成你想要的")
print("=" * 78)
print()
print("  这不是做不到透传, 而是【左板必须声明一个固定身份】:")
print()
print("      * 你在右板插什么键盘, 左板都不知道 —— 它没收到过身份信息")
print("      * 被控机在【枚举那一刻】就要读到 VID/PID, 而那时键盘可能还没插")
print("      * 所以只能是固定值")
print()
print("  当前值:")
print("      VID:PID   = 3554:FA09   (抄的真键盘接收器)")
print("      序列号    = 000000000001")
print("      厂商/产品 = Wired Keyboard / USB Keyboard")
print()
print("  可以做的调整:")
print("      * 改成别的 VID/PID (你说过担心 vid 对不上被封)")
print("      * 序列号改成唯一值(多台设备同时插不会冲突)")
print("      * 厂商/产品名对齐真键盘")
print()
print("  ★ 要真正透传身份, 唯一办法是:")
print("    右板读到真键盘的描述符后, 把 VID/PID 发给左板, 左板重新枚举。")
print("    技术上可行, 但同样有每次上电多一次枚举的代价,")
print("    而且【如果两个键盘 VID 不同, 左板还得跟着变】-> 复杂。")
print()
print("=" * 78)
print("总结: 想做哪个")
print("=" * 78)
print()
print("  性价比排序:")
print("    1. LED 回传        —— 中等工作量, 效果直观 (灯会亮)")
print("    2. VID/PID 改值    —— 几乎零工作量, 告诉我用哪个值即可")
print("    3. 轮询间隔透传    —— 工作量大, 实际收益很小, 建议不做")
