# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("=" * 78)
print("重大发现: Apotheosis 的协议已经写好了, 而且和我的帧格式几乎一样")
print("=" * 78)
print()
print("  文件: C:\\Users\\Administrator\\Desktop\\Apotheosis\\makcu_proto.h")
print()
print("  帧格式对比:")
print()
print("                Apotheosis 协议              我的 kbd_wire.h")
print("   魔数         0xA5 0x5C                    0xA5 0x5C      <- 一样!")
print("   长度字段     len (不含头/CRC)             len            <- 一样")
print("   序号         seq                          seq            <- 一样")
print("   命令/类型    cmd                          type           <- 一样")
print("   CRC          CRC16/MODBUS 低字节在前      CRC16/MODBUS   <- 一样!")
print("   总长         len + 7                      len + 7        <- 一样!")
print()
print("  ★ 也就是说: 我写板间协议时无意中把帧格式做成了和 Apotheosis 一致的。")
print("    这意味着【不需要两套协议】—— 可以直接统一。")
print()
print("=" * 78)
print("Apotheosis 已经定义好的命令 (makcu_proto.h)")
print("=" * 78)
print()
print("  鼠标类:")
print("    0x01 CMD_MOVE           int16 dx, int16 dy         直通位移")
print("    0x02 CMD_MOVE_RAW       原始位移")
print("    0x03 CMD_MOVE_BATCH     批量位移(固件内求和后只输出一次)")
print("    0x04 CMD_MOVETO         绝对移动到")
print("    0x05 CMD_MOVE_CANCEL    清空待发积压(停火)")
print("    0x10 CMD_BUTTON_MASK    u8 mask                    绝对态按键")
print("    0x12 CMD_CLICK          u8 btn, u16 down_ms        固件内定时弹起")
print("    0x20 CMD_WHEEL          int8 delta")
print()
print("  键盘类:  ★ 已经有了!")
print("    0x21 CMD_KEY_MASK       u8 mod + u8 keys[6]        绝对态(标准HID布局)")
print("    0x22 CMD_KEY_TAP        u8 mod + u8 key + u16 ms   单键短按, 固件内自清")
print()
print("  控制类:")
print("    0x40 GET_VERSION   0x41 GET_STATS   0x42 SET_BAUD")
print("    0x43 GHOST_MODE    0x44 PANIC       0x45 REBOOT")
print("    0x48 SUB_ASYNC     订阅按键异步上报")
print()
print("  上报:")
print("    0x84 CMD_ASYNC_BUTTON   u8 real_mask + u8 inj_mask")
print()
print("=" * 78)
print("★★ 关键: 0x43 CMD_GHOST_MODE 就是你要的'屏蔽真实键盘'")
print("=" * 78)
print()
print("  注释里写着: '固件仅返回 ack(0), 无实际行为(占位)'")
print()
print("  也就是说: Apotheosis 上位机【已经会发这个命令】,")
print("            只是当前固件没实现它。")
print()
print("  => 我只要在键盘马克的固件里真正实现 0x43:")
print("       收到 GHOST_MODE(on)  -> 丢弃真实键盘报文")
print("       收到 GHOST_MODE(off) -> 恢复正常透传")
print("     上位机不用改一行代码。")
print()
print("  这正好就是你说的: '屏蔽=丢弃真实键盘报文, 期间上位机也不发'")
print()
print("=" * 78)
print("还有一个意外收获: KEY_TAP 的'固件内定时弹起'")
print("=" * 78)
print()
print("  CMD_KEY_TAP payload: u8 mod + u8 key + u16 hold_ms")
print("  注释: '固件内定时弹起(自清), 所以不会因为上位机异常而把键卡住'")
print()
print("  => 这正是'高性能低延迟 + 不丢命令'的设计:")
print("     上位机只发一次, 固件自己计时弹起, 不依赖上位机的后续命令。")
print("     我要在左板实现这个定时器。")
print()
print("=" * 78)
print("所以最终架构 (一套固件, 自动识别角色)")
print("=" * 78)
print()
print("  右板 (USB Host) —— 两块马克完全一样")
print("    读真设备原始字节 -> 发左板")
print("    转发左板来的注入命令? 不需要, 注入直接进左板")
print()
print("  左板 (USB Device) —— 一块固件, 按插入设备自动切角色")
print("    ┌─ CH343 (上位机) ─> 解析 makcu 协议 (0x01..0x48)")
print("    │                     ├─ 鼠标命令 -> 鼠标 Collection")
print("    │                     ├─ 键盘命令 -> 键盘 Collection")
print("    │                     └─ GHOST_MODE -> 屏蔽标志")
print("    │")
print("    ├─ Serial1 (右板) ─> 真设备原始报文 (透传)")
print("    │                    GHOST 开启时丢弃")
print("    │")
print("    └─ USB-A ─> 被控机 (按角色只暴露键盘 或 只暴露鼠标)")
print()
print("  角色判定:")
print("    右板检测 USB-C 插入的是键盘还是鼠标 -> 告知左板")
print("    左板用完这份信息决定: (a)枚举哪种描述符 (b)如何合并数据")
