# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("=" * 78)
print("★ 你的问题点中要害了 —— 我用错协议的一半")
print("=" * 78)
print()
print("  Apotheosis 里确实有【两套】, 但它们是【配合使用】的, 不是二选一:")
print()
print("    Makcu.cpp    / Makcu.h      <- 旧的 makcu::Device (走 modules/makcu)")
print("    MakcuNew.cpp / MakcuNew.h   <- 新的直通协议, 【当前使用】")
print()
print("  MakcuNew 用的是 makcu_proto.h 里的【二进制帧】 —— 这部分我做对了。")
print()
print("  但是!! 【首次连接握手】和【mask 屏蔽】走的是【ASCII 文本通道】,")
print("  这部分我【完全没实现】, 而且我还用二进制帧去实现 mask, 是错的。")
print()
print("=" * 78)
print("我从 MakcuNew.cpp 里读到的确切行为")
print("=" * 78)
print()
print("  1) 连接握手 (第 113 行)")
print("       probeAscii(\"km.version\", \"MAKCU-PASSTHROUGH\", 500)")
print()
print("     => 上位机发 ASCII 串 \"km.version\"")
print("        固件必须回一行包含 \"MAKCU-PASSTHROUGH\" 的文本")
print("        不回 -> 上位机判定连接失败, 【整个连接流程中止】")
print()
print("     ★ 这是最致命的: 我现在的固件只在收到二进制帧后静音日志,")
print("       对 \"km.version\" 这种 ASCII 命令【完全不理会】,")
print("       => Apotheosis 根本连不上!")
print()
print("  2) 波特率协商 (第 127 行)")
print("       kBootBaud 先试, 若与 requestedBaud 不同:")
print("         发二进制 CMD_SET_BAUD(0x42) 请求切波特率")
print("         等 250ms, 重连, 再 probeAscii 确认")
print()
print("     => 所以 0x42 SET_BAUD 是【必须实现】的, 我之前写成'暂不实现'")
print()
print("  3) mask 屏蔽 (第 651-693 行)")
print("       mask(N)    -> 发 ASCII: \"km.mask(N)\\r\\n\"   (N 钳到 2000ms)")
print("       maskOff()  -> 发 ASCII: \"km.maskoff\\r\\n\"")
print()
print("     ★ 注释明确写着: '走 ASCII 文本通道, 不新增二进制帧'")
print("       我却用二进制 0x43 GHOST_MODE 去实现 —— 方向错了")
print()
print("       而且注释还说明: 固件收到后要【经板间 UART 转发给 fw_host】,")
print("       由 fw_host 在其 mask 窗口内丢弃真实输入。")
print("       也就是屏蔽【在右板执行】, 不是左板。")
print()
print("  4) 固件应答规则 (注释原文)")
print("       '固件对这条命令只回一行 \"km.mask(N) ok\" 到板间链路,")
print("        不会回到本串口(设备侧的 ASCII 应答仅对 km.version 等命令发出)'")
print()
print("     => ASCII 命令的应答: 只有 km.version 需要回, 其它不必")
print("     => 二进制命令: 一律不回应答 (ACK-free)")
print()
print("=" * 78)
print("所以我必须做的修正")
print("=" * 78)
print()
print("  [必须] 1. 实现 ASCII 命令通道 (CH343 上):")
print("            km.version  -> 回 \"MAKCU-PASSTHROUGH ...\"")
print("            km.mask(N)  -> 转给右板, 右板丢弃真实输入 N 毫秒")
print("            km.maskoff  -> 解除")
print()
print("  [必须] 2. 实现 0x42 CMD_SET_BAUD (切波特率)")
print()
print("  [修正] 3. mask 从'左板本地丢弃' 改成'转发给右板执行'")
print("            (按注释的设计, 屏蔽在 fw_host 侧)")
print()
print("  [保留] 4. 二进制帧解析 (0x01~0x48) —— 这部分是对的")
print()
print("  [保留] 5. 日志静音 —— 但现在要改判据:")
print("            不是'收到二进制帧'才静音, 而是'连接建立后'就静音")
print("            因为 km.version 是 ASCII 的, 它本身就说明上位机在跟我说话")
print()
print("=" * 78)
print("★ 这解释了为什么'连不上'是最关键的一步")
print("=" * 78)
print()
print("  如果 Apotheosis 连不上, 它连注入命令都不会发。")
print("  所以 km.version 应答是整个链路的【第一道门】。")
print()
print("  我需要确认一件事: kBootBaud 是多少? 这决定握手的初始波特率。")
