# -*- coding: utf-8 -*-
"""
关键时序分析: 左板枚举发生在【什么时候】?
如果左板在收到右板的 VID/PID 之前就枚举完了, 动态 VID 就无效。
"""
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("=" * 78)
print("时序分析: 这是方案成败的关键")
print("=" * 78)
print()
print("你的操作顺序:")
print("   1. 先插 USB-C (真键盘 -> 右板)")
print("   2. 再插 USB-A (左板 -> 被控机) 通电")
print()
print("这个顺序【对你有利】, 因为:")
print("   * 插 USB-A 才通电 -> 左板才开始跑 -> 才开始枚举")
print("   * 而那时右板【可能已经】读完真键盘的描述符了")
print()
print("但是有个隐患: 两块板是【同一块 PCB】, 插 USB-A 时右板才上电。")
print("   => 右板也要在左板枚举前完成 读真键盘描述符 这一步。")
print()
print("=" * 78)
print("真实时序 (两块板同时上电)")
print("=" * 78)
print()
print("  t=0ms    插 USB-A, 两芯片同时上电")
print("  t~300ms  右板: usbHost.begin() -> USB Host 开始枚举真键盘")
print("  t~500ms  右板: 收到 USB_DEVICE_DESC -> 拿到 VID/PID  <-- 关键")
print("  t~500ms  左板: 还在 setup() 前的初始化")
print("  t~???ms  左板: tinyusb_init() -> 被控机开始读描述符")
print()
print("  ★ 问题: 左板的 tinyusb_init() 在 setup() 里, 上电后很快就执行,")
print("    很可能【早于】右板读完真键盘描述符。")
print()
print("=" * 78)
print("解决办法: 让左板等一下")
print("=" * 78)
print()
print("  在左板的 setup() 里:")
print("      1) 先启动 Serial1")
print("      2) 等右板发来 VID/PID (带超时, 比如 1500ms)")
print("      3) 再用收到的值调 tinyusb_init()")
print()
print("  超时后用内置默认值(3554:FA09), 保证即使右板没响应也能工作。")
print()
print("  代价: 开机多等最多 1.5 秒。")
print("  收益: 被控机看到的 VID/PID = 你真键盘的 VID/PID。")
print()
print("=" * 78)
print("实现要点")
print("=" * 78)
print()
print("  协议: 新增帧类型 0x25 = 设备身份")
print("        payload = idVendor(2) + idProduct(2) + bcdDevice(2) = 6 字节")
print()
print("  右板: onConfig 里拿到 descriptor_device.idVendor/idProduct 后,")
print("        通过 Serial1 发一帧 0x25")
print()
print("  左板: setup() 里阻塞等这一帧(或超时), 拿到后存进全局,")
print("        usb_desc.cpp 的 desc_device 用它而不是写死的常量")
print()
print("  注意: usb_desc.cpp 里的 desc_device 是 const 全局,")
print("        要改成运行时可变(非 const), 在枚举前填好。")
