# -*- coding: utf-8 -*-
"""对比两版固件的报告描述符结构 —— 这是键盘能否被识别的根本原因"""
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("=" * 78)
print("旧版 (MAKCUNEW) 的报告描述符: Arduino USBHID 自动拼接")
print("=" * 78)
print()
print("  装配过程 (USBHID.cpp:154 tinyusb_load_enabled_hid_devices):")
print()
print("      for(i=0; i<已注册的HID设备数; i++)")
print("          长度 = tinyusb_on_add_descriptor(i, dst)")
print("          dst += 长度")
print()
print("  => 把【每个已注册设备】的报告描述符【首尾拼接】成一个 blob")
print()
print("  关键: 注册了哪些设备, 由 USBHIDMouse::begin() / USBHIDKeyboard::begin() 决定")
print()
print("  旧左板 InitUSB() 的逻辑 (按右板标记):")
print("      wantKbd   -> Kbd.begin()    只注册键盘")
print("      wantMouse -> Mouse.begin()  只注册鼠标")
print()
print("  ★ 问题就在这里: 如果【两个都注册了】, 拼接结果是:")
print()
print("      05 01 09 06 ... 键盘 collection (无 Report ID)")
print("      05 01 09 02 ... 鼠标 collection (无 Report ID)")
print()
print("    两个 collection 都【没有 Report ID】-> 无法区分!")
print("    被控机拿到这份描述符, 解析出的两个 collection 共用同一个 report ID(0)")
print("    -> 键盘和鼠标的报告互相冲突 -> 键盘不可用")
print()
print("=" * 78)
print("新版 (KBD_PASSTHROUGH) 的报告描述符: 我手写的, 明确用 Report ID 区分")
print("=" * 78)
print()
print("     键盘 Collection 前面: 85 01   (Report ID = 1)")
print("     鼠标 Collection 前面: 85 02   (Report ID = 2)")
print()
print("  而且我把接口协议设成了 Boot Keyboard:")
print("     TUD_HID_DESCRIPTOR(..., HID_ITF_PROTOCOL_KEYBOARD, ...)")
print("       -> SubClass=01(Boot), Prot=01(Keyboard)")
print()
print("  旧版用的是 TUD_HID_INOUT_DESCRIPTOR(..., HID_ITF_PROTOCOL_NONE, ...)")
print("       -> SubClass=00, Prot=00(无)")
print()
print("=" * 78)
print("所以旧版为什么不行 —— 三个叠加原因")
print("=" * 78)
print()
print("  1) 报告描述符是拼接的, 且两个 collection 都没有 Report ID")
print("     -> 被控机无法区分键盘/鼠标报告")
print()
print("  2) 接口协议是 NONE (SubClass=00/Prot=00), 不是 Boot Keyboard")
print("     -> 与真键盘的 MI_00 (Class_03/Sub_01/Prot_01) 结构不符")
print()
print("  3) 键盘报文走 Kbd.press()/release() 的【差分】方式")
print("     -> 每个键单独一次报文, 而不是真键盘的【完整快照】")
print("     -> 主机看到的状态序列与真键盘不一致")
print()
print("=" * 78)
print("新版为什么行")
print("=" * 78)
print()
print("  [OK] 手写描述符, 两个 Collection 各带明确 Report ID (1 / 2)")
print("  [OK] 接口协议 = Boot Keyboard, 与真设备 MI_00 一致")
print("  [OK] 键盘报文是【完整快照】, 每次按键变化重发全量 8 字节")
print("  [OK] 原始字节透传, 不经过任何按键解析")
print("  [OK] bDeviceClass=0x00 -> usbccgp")
