# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("=" * 78)
print("旧版 (MAKCUNEW) vs 新版 (KBD_PASSTHROUGH) —— 逐层对比")
print("=" * 78)
print()
print("  层             旧版 MAKCUNEW              新版 KBD_PASSTHROUGH")
print("  -------------  -------------------------  --------------------------")
print("  HID 封装       Arduino USBHID 库           完全绕开, 手写 TinyUSB")
print("  报告描述符     运行时 malloc 拼接生成       编译期常量, 我手写")
print("  描述符回调     Arduino 提供(43个符号)       我提供(1个符号)")
print("  接口协议       HID_ITF_PROTOCOL_NONE       HID_ITF_PROTOCOL_KEYBOARD")
print("                 (SubClass=00/Prot=00)       (SubClass=01/Prot=01)")
print("  端点           INOUT (IN+OUT 两条)         只有 IN")
print("  键盘发射       Kbd.press()/release() 差分   完整快照, 原样透传")
print("  bDeviceClass   由 Arduino 配置              0x00 (usbccgp)")
print()
print("=" * 78)
print("为什么旧版不行 —— 我原先猜错了一半, 这里是核实后的结论")
print("=" * 78)
print()
print("  【先纠正我自己的一个错误判断】")
print("    我本来以为旧版两个 Collection 都没 Report ID。")
print("    查证后发现: Arduino 其实【有】Report ID,")
print("    而且 HID_REPORT_ID_KEYBOARD=1 / HID_REPORT_ID_MOUSE=2,")
print("    数值和新版一样。所以 Report ID 不是差异点。")
print()
print("  【真正的差异 1: 接口协议是 NONE】★ 最可能的主因")
print()
print("    旧版 (USBHID.cpp:211):")
print("        TUD_HID_INOUT_DESCRIPTOR(*itf, str_index,")
print("                                  HID_ITF_PROTOCOL_NONE, ...)")
print("        -> bInterfaceSubClass = 0, bInterfaceProtocol = 0")
print()
print("    真键盘接收器的 MI_00:")
print("        Class_03 / SubClass_01 / Prot_01   (Boot Keyboard)")
print()
print("    新版:")
print("        TUD_HID_DESCRIPTOR(..., HID_ITF_PROTOCOL_KEYBOARD, ...)")
print("        -> SubClass=01 / Prot=01  ★ 与真设备一致")
print()
print("  【真正的差异 2: 报告描述符是运行时拼接的】")
print()
print("    旧版 tinyusb_load_enabled_hid_devices():")
print("        malloc 一块缓冲, 把每个已注册设备的描述符【首尾拼接】")
print("        -> 拼接结果依赖【注册顺序】和【哪些设备注册了】")
print("        -> 一旦 wantKbd/wantMouse 判断有偏差, 描述符就变样")
print("        -> 而且 malloc 出来的缓冲, 生命周期和内容都更脆弱")
print()
print("    新版: 编译期常量数组, 内容固定可验证(有 parse_desc.py 校验)")
print()
print("  【真正的差异 3: 键盘发射方式是差分而非快照】")
print()
print("    旧版 kbdEmitMerged() 算 delta, 然后逐键 Kbd.press()/release()")
print("        -> 每个键变化单独发一次报文")
print("        -> 真键盘是【每次变化重发完整 8 字节快照】")
print("        -> 主机看到的状态序列与真设备不同")
print()
print("    新版: 直接发真键盘的原始 8 字节, 一个 bit 不改")
print()
print("  【差异 4: 是否是复合设备】")
print()
print("    旧版 bDeviceClass 由 Arduino 配置 -> 单接口 HidUsb")
print("    新版 0x00 -> usbccgp, 与真键盘接收器的父设备驱动一致")
print()
print("=" * 78)
print("最根本的一句话")
print("=" * 78)
print()
print("  旧版是在【Arduino USBHID 的框架里绕】—— 它只能产生一个固定形态的")
print("  接口, 描述符还是运行时拼的。绕不过去就只能改数据通路(差分/快照),")
print("  治标不治本。")
print()
print("  新版是【完全绕开 Arduino 的 USB 封装, 直接写 TinyUSB 描述符】——")
print("  接口协议、端点、Collection、Report ID 全部自己控制, 想跟真设备")
print("  一致就能一致。")
print()
print("  加上数据通路改成【原样字节透传】, 不再有按键解析这一层可能出错的环节。")
print()
print("=" * 78)
print("但是 —— 诚实地说, 我无法 100% 确定旧版失败的唯一主因")
print("=" * 78)
print()
print("  上面 4 条差异都是真实的, 但我没有做过【只改一条】的对照实验。")
print("  理论上差异 1 (接口协议 NONE vs Boot Keyboard) 嫌疑最大,")
print("  因为 Windows 对 Boot 协议键盘的处理路径不同。")
print()
print("  如果你想要确定答案, 可以做这个实验:")
print("    把新版固件的接口协议从 HID_ITF_PROTOCOL_KEYBOARD 改成 NONE,")
print("    其他不动, 重新编译测试。")
print("      -> 如果键盘失效 = 确认差异 1 是主因")
print("      -> 如果键盘仍可用 = 主因在别处(差异 2/3/4)")
print()
print("  要我做这个对照实验吗?")
