# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("=" * 72)
print("时间线梳理")
print("=" * 72)
print()
print("  测试1: 左板=修复8(双HID) + 右板=修复6     -> 鼠标回归(灯闪不动)")
print("  测试2: 左板=修复8(双HID) + 右板=修复9     -> 还是不行")
print()
print("=" * 72)
print("矛盾分析")
print("=" * 72)
print()
print("  修复9 修的是【右板】的鼠标解码兜底:")
print("      md.xAxisSize==0 && md.yAxisSize==0 -> 用标准布局 1/2/3")
print()
print("  如果修复9 生效, 鼠标【至少应该能按标准布局动】。")
print("  但你说还是不行 -> 说明问题不在右板的解码兜底, 而在别处。")
print()
print("=" * 72)
print("最可能的原因: 左板修复8 (双HID接口) 破坏了 USB 描述符")
print("=" * 72)
print()
print("  修复8 做了什么:")
print("    1) 用 USB_INTERFACE_CUSTOM 注册第二个接口")
print("    2) 加 -Wl,--wrap=tud_hid_descriptor_report_cb")
print("    3) 键盘发送改走 instance 1")
print()
print("  风险点 A: 配置描述符总长变化")
print("    框架: tinyusb_config_descriptor_len += descriptor_len")
print("    我传 TUD_HID_DESC_LEN = 25")
print("    回调返回 TUD_HID_DESC_LEN = 25  -> 一致, 应该没问题")
print()
print("  风险点 B: 接口数变为 2, 但被控机可能不接受")
print()
print("  风险点 C: ★ 端点位图耗尽")
print("    max_endpoints = 4 (有 FIFO 的端点上限)")
print("    Arduino HID(INOUT) 用 2 个: ep_in + ep_out")
print("    我的接口再要 1 个 ep_in -> 共 3 个")
print("    => 在 4 以内, 应该 OK")
print()
print("  风险点 D: ★★ dualHidBegin() 注册失败 -> 框架 load_descriptor 返回 0")
print("    tinyusb_load_enabled_interfaces() 里:")
print("        len = load_descriptor(CUSTOM, ...)")
print("        if (!len) { log_e(\"Descriptor Load Failed\"); return false; }")
print("    => 返回 false -> USB 初始化【整体失败】!")
print("    => 鼠标键盘全部失效!")
print()
print("    我的 dualHidLoadDescriptor 里有可能返回 0 的路径:")
print("        if (s_registered) return 0;              <- 二次调用会返回0")
print("        if (ep_in == 0) return 0;                <- 端点耗尽会返回0")
print()
print("    ★ 但注意: USBHID 的构造可能在【全局对象构造期】就调用了")
print("      tinyusb_enable_interface(USB_INTERFACE_HID, ...)")
print("      而我的 dualHidBegin() 是在 InitUSB() 里调的")
print("      两者都在 USB.begin() 之前 -> 顺序 OK")
