# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("=" * 72)
print("方案 A 可行性评估 (基于已读到的框架源码)")
print("=" * 72)
print()
print("### 目标 ###")
print("左板暴露成【多接口复合设备】, 使 Windows 用 usbccgp 加载,")
print("结构上与真键盘接收器一致。")
print()
print("### 已确认的框架事实 ###")
print()
print("1) tinyusb_enable_interface() 每种接口类型只能注册一次")
print("   (tinyusb_loaded_interfaces_mask 位检查)")
print("   -> USB_INTERFACE_HID 槽已被 Arduino USBHID 占用")
print()
print("2) 但 USB_INTERFACE_CUSTOM 是【独立空槽】, 可用")
print("   tinyusb_load_descriptor() 会回调我们注册的函数:")
print("       if(tinyusb_loaded_interfaces_callbacks[interface])")
print("           return callbacks[interface](dst, itf);")
print("   -> 我们可以在里面写入【第二个 HID 接口描述符】")
print()
print("3) 端点预算: 最多 4 个 FIFO")
print("   当前 HID(INOUT) 用 2 个 (ep_out + ep_in)")
print("   再加 1 个 HID 接口的 IN 端点 -> 3 个, 够用")
print()
print("4) CFG_TUD_HID 已经是 2 -> TinyUSB 层面允许 2 个 HID instance")
print()
print("### 关键难点 ###")
print()
print("A. 报告描述符分发")
print("   Arduino 的 tud_hid_descriptor_report_cb(instance) 无脑返回")
print("   同一个拼接缓冲 -> 两个接口会拿到同样的描述符。")
print("   必须【重写】该回调, 按 instance 返回不同的描述符。")
print("   但框架源文件参与编译 -> 会 multiple definition (原作者已踩过)")
print()
print("B. 发送通道")
print("   Arduino 的 SendReport 写死 tud_hid_n_report(0, ...)")
print("   -> 键盘报文需要走【instance 1】, 必须绕过 Arduino 直接调")
print("      tud_hid_n_report(1, report_id, buf, len)")
print()
print("C. GET/SET_REPORT 回调")
print("   同样需要按 instance 分发, 否则 SET_REPORT(LED) 会走错接口")
print()
print("D. 设备描述符 bDeviceClass")
print("   真键盘父设备是 usbccgp -> bDeviceClass=0x00(由接口定义)")
print("   需要确认 Arduin 侧 USB.usbClass() 设置正确")
print()
print("### 落地路径 (按风险从低到高) ###")
print()
print("步骤1: 用 USB_INTERFACE_CUSTOM 注册第二接口的描述符")
print("       -> 只需改 USBSetup.cpp, 不碰框架文件")
print("步骤2: 重写 tud_hid_*_cb 系列回调, 按 instance 分发")
print("       -> 需要 __wrap 或弱符号技巧, 或直接改框架源")
print("步骤3: 键盘发送改走 tud_hid_n_report(1, ...)")
print()
print("### 风险 ###")
print(" - 步骤2 若无法覆盖, 整个方案受阻(框架源参与编译)")
print(" - 鼠标通路可能回归(当前单接口方案是好的)")
print(" - 需要多轮真机验证")
