# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("=" * 72)
print("方案 A 可行性: 决定性证据")
print("=" * 72)
print()
print("### map 文件第 1-6 行 ###")
print()
print("  Archive member included to satisfy reference by file (symbol)")
print("  .pio\\build\\LEFT\\lib8c9\\libUSB.a(USBHIDKeyboard.cpp.o)")
print("      <- 被引用于 .pio\\build\\LEFT\\src\\USBSetup.cpp.o (USBHIDKeyboard::USBHIDKeyboard())")
print("  .pio\\build\\LEFT\\lib8c9\\libUSB.a(USBHIDMouse.cpp.o)")
print("      <- ...")
print()
print("### 这条记录说明了什么 ###")
print()
print("归档成员是按【符号引用】按需拉取的, 而不是全部无条件链接。")
print()
print("  src/*.o 先参与链接 (项目源码)")
print("  然后链接器发现有未定义符号 (如 USBHIDKeyboard::USBHIDKeyboard)")
print("  才去 libUSB.a 里找【定义了该符号的成员】并拉入")
print()
print("### 对覆盖的意义 ###")
print()
print("tud_hid_descriptor_report_cb 定义在 USBHID.cpp.o 里。")
print("如果项目 src 里【也定义了】这个符号:")
print()
print("  - 链接器先看 src/*.o -> 已找到定义 -> 不再当作未定义符号")
print("  - USBHID.cpp.o 这个归档成员【仍会被拉入】(因为 USBHID::begin 等")
print("    符号只有它有), 但那时它带来的 tud_hid_descriptor_report_cb")
print("    就会与项目里的定义【冲突: multiple definition】")
print()
print("### 结论 ###")
print()
print("直接重定义【不行】—— 原作者踩的就是这个坑, 他的注释是准确的。")
print()
print("### 但是 ###")
print()
print("还有两条可行路径:")
print()
print("路径1: 覆盖整个 USB 库 (lib_deps 提供本地 USB 库替代框架库)")
print("       -> PlatformIO 会用项目里的库, 框架库不再被链接")
print("       -> 但 USB 库依赖框架内部头文件, 替换风险高")
print()
print("路径2: 不用第二个 Arduino HID 接口, 改用 USB_INTERFACE_CUSTOM")
print("       -> CUSTOM 是空槽, 描述符由【我们的回调】写")
print("       -> 该接口的 instance 由 TinyUSB 分配")
print("       -> 需要自己的 tud_hid_*_cb, 而这些是 TU_ATTR_WEAK!")
print()
print("       ★ 关键: 查 hid_device.h 里各回调的弱属性")
