# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("=== 关键: 0x23 帧的 LEN 字段语义 ===")
print()
print("右板发送 (serial1SendKeyboardBinary):")
print("  len = 1 + keyCount = 1 + 6 = 7")
print("  s_tx_frame[2] = len = 7")
print("  payload = s_tx_frame[5..11] = [mod, k0..k5] = 7 字节")
print("  CRC over s_tx_frame[2 .. 2+3+7-1] = [2..11]  共 10 字节")
print("  s_tx_frame[12],[13] = CRC")
print("  Serial1.write(..., len + 7) = 14 字节")
print()
print("设备侧解析 (proto_parser.cpp):")
print("  WAIT_LEN_A5: _len = b = 7")
print("               _need = 3 + _len + 2 - 1 = 11")
print("  GET_REST_A5: 收 11 字节后:")
print("               calc = crc16_modbus(_raw + 2, 3 + _len) = crc(_raw[2..11], 10 字节)")
print("               rx   = _raw[5+_len] | (_raw[6+_len] << 8) = _raw[12] | _raw[13]<<8")
print("               dispatchA5(_raw[3], _raw[4], _raw + 5, _len)")
print()
print("  总接收字节 = 2(头) + 11 = 13")
print("  但右板写了 14 字节!")
print()
print("=== 计算核对 ===")
print("  帧总长应为: 2 + 1(LEN) + 1(SEQ) + 1(CMD) + LEN + 2(CRC)")
print("            = 2 + 1 + 1 + 1 + 7 + 2 = 14")
print("  但解析器只消费: 2 + _need = 2 + 11 = 13")
print()
print("  差值 = 1 字节!")
print()
print("=== _need 公式 ===")
print("  _need = 3 + _len + 2 - 1 = _len + 4 = 11")
print("  解析器认为: 2(POS后) + 11 = 13 字节一帧")
print("  _need 是从 WAIT_LEN_A5 消费掉 LEN 之后还要收的字节数")
print("    剩余 = SEQ(1) + CMD(1) + PAYLOAD(len) + CRC(2) = len + 4")
print("    len=7 -> 11  ✓ 与 _need 一致")
print()
print("  总长 = 2(头) + 1(LEN) + 11 = 14  ✓ 与写入一致!")
print()
print("=> LEN 语义正确, 帧长正确")
