# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("=" * 70)
print("决定性对比: 真设备直插  VS  经马克克隆")
print("=" * 70)
print()
print("### 键盘接收器 VID_3554 (端口6直插 / 端口5经马克) ###")
print()
print("  位置         状态      服务        含义")
print("  ----------   -------   ---------   ------------------------")
print("  端口6 直插   OK        usbccgp     复合设备驱动 (真设备)")
print("  端口5 马克   Unknown   HidUsb      单一HID (克隆, 被简化)")
print()
print("### 鼠标接收器 VID_249A ###")
print()
print("  位置         状态      服务        含义")
print("  ----------   -------   ---------   ------------------------")
print("  6&48066CA    Unknown   HidUsb      !! 注意: 鼠标【直插】也是 HidUsb !!")
print()
print("=" * 70)
print("关键结论")
print("=" * 70)
print()
print("1) 键盘接收器: 直插=usbccgp(复合), 克隆后=HidUsb(单一)")
print("   -> 马克把【复合设备】简化成了【单一HID】")
print()
print("2) 鼠标接收器: 直插本身就是 HidUsb")
print("   -> 马克克隆后也是 HidUsb, 结构【一致】")
print("   -> 所以鼠标能用!")
print()
print("=> 这解释了为什么鼠标正常而键盘不行:")
print("   鼠标设备的真实结构本来就是单一HID, 克隆后一致;")
print("   键盘设备的真实结构是复合设备(usbccgp + 多接口),")
print("   而马克只能产生单一HID -> 结构不符 -> 键盘不被识别。")
print()
print("=" * 70)
print("证据: 真键盘(端口6)的接口分解")
print("=" * 70)
print()
print("  USB\\VID_3554&PID_FA09\\5&15C311E1&0&6   [OK] svc=usbccgp")
print("    ├─ MI_00   [HidUsb] -> Keyboard Device")
print("    └─ MI_01   [HidUsb] -> 6 collections")
print("           COL04 Keyboard / COL05 Mouse / 媒体键 / 供应商 ...")
print()
print("  => 真键盘是【2个独立USB接口】的复合设备")
print("  => 马克只产生【1个HID接口】")
