# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("=" * 72)
print("鼠标回归根因 (老版修复6 右板)")
print("=" * 72)
print()
print("### 修复6 引入的两个改动 ###")
print()
print("  改动A: iface_report_desc[slot] 按接口存描述符")
print("  改动B: 全局 HIDReportDesc 只在 isMouse 为 true 时写入")
print()
print("### 鼠标解码路径 ###")
print()
print("  const HIDReportDescriptor &md =")
print("      (ifaceValid && ifaceOfFrame < kMax && iface_descValid[ifaceOfFrame])")
print("          ? iface_report_desc[ifaceOfFrame]")
print("          : HIDReportDesc;              // <-- 回退到全局")
print()
print("### 失败链 ###")
print()
print("  情形1: iface_descValid[ifaceOfFrame] == false")
print("     -> md = HIDReportDesc (全局)")
print("  情形2: isMouse == false 时全局从不被写")
print("     -> HIDReportDesc 保持 = {} (全零)")
print("     -> buttonStartByte=0, xAxisStartByte=0, yAxisStartByte=0, wheelStartByte=0")
print("     -> report.x = data_buffer[0] & ... ")
print()
print("  ★ 若 mouse 描述符的字节序列不精确匹配 '05 01 09 02',")
print("    isMouse 恒为 false -> 全局永远全零 -> 位移异常")
print()
print("### 为什么灯还闪 ###")
print()
print("  flashLED() 在 has_data 分支里, 早于鼠标解码 -> 灯照闪")
print("  只有 report.x/y 计算受影响 -> 光标不动")
print("  => 与实测现象(亮灯不移动)完全吻合")
print()
print("=" * 72)
print("修法")
print("=" * 72)
print()
print("  1) 放宽全局回退条件: 只要该接口的描述符【已解析成功】就写全局,")
print("     不再要求 isMouse。因为能到达这里的就是 HID 接口的描述符,")
print("     鼠标设备只会送来鼠标描述符。")
print()
print("  2) 更稳妥: 鼠标解码时若 iface_report_desc 不可用,")
print("     且全局也为零(xAxisSize==0), 则用【内置默认布局】兜底")
print("     (标准 3 字节鼠标: buttons@0, x@1, y@2, wheel@3)")
print()
print("  3) 同时保留按接口取值 —— 复合设备时每个接口用自己的描述符")
