# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("=" * 72)
print("路线确认: 用 USB_INTERFACE_CUSTOM 添加第二个 HID 接口")
print("=" * 72)
print()
print("### 现有 HID 接口 (Arduino USBHID) ###")
print()
print("  USBHID::USBHID() {")
print("      tinyusb_enable_interface(USB_INTERFACE_HID, TUD_HID_INOUT_DESC_LEN,")
print("                               tusb_hid_load_descriptor);")
print("  }")
print()
print("  tusb_hid_load_descriptor(dst, itf):")
print("      if(tinyusb_hid_is_initialized) return 0;   // 只允许一次")
print("      写入 TUD_HID_INOUT_DESCRIPTOR(*itf, ..., desc_len, ep_out, ep_in, 64, 1)")
print("      *itf += 1")
print()
print("### 我的第二个接口 (CUSTOM 槽) ###")
print()
print("  tinyusb_enable_interface(USB_INTERFACE_CUSTOM, LEN, my_load_descriptor)")
print()
print("  my_load_descriptor(dst, itf):")
print("      写入 TUD_HID_DESCRIPTOR(*itf, str, HID_ITF_PROTOCOL_KEYBOARD,")
print("                              my_kbd_desc_len, ep_in, 64, 1)")
print("      *itf += 1")
print()
print("### 描述符顺序 (按 interface_t 枚举值) ###")
print()
print("  for(i=0; i<USB_INTERFACE_MAX; i++)")
print("      if (mask & BIT(i)) load_descriptor(i, dst, &num)")
print()
print("  枚举值: MSC=0 DFU=1 HID=2 VENDOR=3 CDC=4 MIDI=5 CUSTOM=6")
print("  => HID(2) 先于 CUSTOM(6) 装载")
print("  => 接口0 = Arduino HID(鼠标+键盘拼接)")
print("     接口1 = 我们的纯键盘接口")
print()
print("### 报告描述符如何按 instance 分发? ###")
print()
print("  tud_hid_descriptor_report_cb(instance) 是【非weak】, 无法覆盖。")
print("  但 TinyUSB 的 hid_device.c 里, GET_DESCRIPTOR(Report) 的处理:")
print("      desc = tud_hid_descriptor_report_cb(instance)")
print("  Arduino 的实现【忽略 instance】, 两个接口都会拿到同一个拼接描述符。")
print()
print("  ★ 这才是真正要解决的问题。")
print()
print("### 可行解: 让两个接口共用同一份描述符 ###")
print()
print("  既然 Arduino 无条件返回同一份拼接描述符(Mouse+Kbd), 那就顺水推舟:")
print("    接口0: 声明 wReportLength = 拼接总长 (Arduino 已做)")
print("    接口1: 也声明同样的 wReportLength")
print("  两者都会拿到同一份描述符 -> 两个接口各有一套 Mouse+Kbd collection")
print("  Windows 会看到【2个HID接口, 每个都含鼠标+键盘】")
print()
print("  这样 usbccgp 结构成立(多接口), 且两个接口都能收报文。")
print("  但和真键盘(MI_00=键盘, MI_01=多媒体/鼠标)结构仍不完全一致。")
