# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("=" * 62)
print("键盘路径完整追踪")
print("=" * 62)
print()
print("右板 (fw_host):")
print("  _onReceive -> ifaceIsKeyboard -> onKeyboardSnapshot")
print("    -> serial1SendKeyboardBinary -> A5 5C | LEN | SEQ | 0x23 | ...")
print()
print("左板 (fw_device) serial1RX:")
print("  1. byte == 0xA5 ? -> s_s1_stage[0] 暂存, S1_BIN_STAGE1")
print("  2. byte == 0x5C ? -> s_s1_bin_state = S1_BIN_FRAME")
print("                        g_proto1.feed([0xA5,0x5C], 2)")
print("  3. 后续字节全部 g_proto1.feed(1)")
print("  4. g_proto1.atFrameBoundary() -> 回 S1_BIN_IDLE")
print()
print("  g_proto1 解析 -> dispatchA5(_raw[3], _raw[4], _raw+5, _len)")
print("    cmd = 0x23 -> case 0x23:")
print("      keys[0..5] = pl[1..6]")
print("      onKbReport(pl[0], keys)")
print()
print("  g_proto1.onKbReport = kbdApplyRealReport")
print("    -> 存 s_kbd_mod_real / s_kbd_keys_real")
print("    -> kbdEmitMerged()")
print("      -> Kbd.press()/release() 或 sendClonedKbdReport")
print()
print("=" * 62)
print("可疑点逐一核对")
print("=" * 62)

src = open(r'_fix1_build\src\esp_usb_host.cpp', encoding='utf-8', errors='replace').read()

print()
print("[1] 键盘帧 LEN = 1 + keyCount")
print("    keyCount 固定传 6 -> len = 7")
print("    payload 实际写入: s_tx_frame[5]=mod, [6..11]=keys  -> 7 字节 OK")
print()
print("[2] s_tx_frame[6+i] 写入循环")
i = src.find('serial1SendKeyboardBinary')
seg = src[i:i+1200]
print("    循环写 keys:", 'for (uint8_t i = 0; i < keyCount; ++i)' in seg)
print("    写入位置 6+i:", 's_tx_frame[6 + i]' in seg)
print()
print("[3] CRC 覆盖范围")
print("    crcStart=2, crcLen=3+len=10 -> 覆盖 [2..11]")
print("    CRC 写入位置: [2+10]=[12], [13]")
print("    总写入 len+7 = 14  -> OK")
