# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("=" * 72)
print("接口编号 / bNumInterfaces 追踪 (关键正确性验证)")
print("=" * 72)
print()
print("框架代码:")
print("  static uint8_t tinyusb_loaded_interfaces_num = 0;   // 既是 itf, 又是 bNumInterfaces")
print()
print("  for(i=0; i<USB_INTERFACE_MAX; i++)")
print("      if (mask & BIT(i))")
print("          len = load_descriptor(i, dst, &tinyusb_loaded_interfaces_num);")
print("          dst += len;")
print()
print("  TUD_CONFIG_DESCRIPTOR(1, tinyusb_loaded_interfaces_num, ...)")
print("                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^ bNumInterfaces")
print()
print("-" * 72)
print("装载顺序 (枚举值): MSC=0 DFU=1 HID=2 VENDOR=3 CDC=4 MIDI=5 CUSTOM=6")
print("-" * 72)
print()
print("  本工程只启用: HID(2) + CUSTOM(6)")
print()
print("  第1轮 i=2 (HID):")
print("      *itf = 0  -> tusb_hid_load_descriptor 写 TUD_HID_INOUT_DESCRIPTOR(0, ...)")
print("      *itf += 1 -> itf = 1")
print()
print("  第2轮 i=6 (CUSTOM):")
print("      *itf = 1  -> dualHidLoadDescriptor 写 TUD_HID_DESCRIPTOR(1, ...)")
print("      *itf += 1 -> itf = 2")
print()
print("  最终 bNumInterfaces = 2   ✓ 正确")
print()
print("-" * 72)
print("TinyUSB 的 HID instance 分配")
print("-" * 72)
print()
print("  TinyUSB 按【HID 接口在配置描述符中出现的顺序】分配 instance:")
print("    第1个 HID 接口 -> instance 0")
print("    第2个 HID 接口 -> instance 1")
print()
print("  接口0 (Arduino, TUD_HID_INOUT) 先写入 -> instance 0")
print("  接口1 (我的,   TUD_HID)        后写入 -> instance 1   ✓")
print()
print("  所以 dualHidSendKeyboard 里的 tud_hid_n_report(1, ...) 正确")
print()
print("-" * 72)
print("报告描述符分发 (--wrap)")
print("-" * 72)
print()
print("  __wrap_tud_hid_descriptor_report_cb(instance):")
print("      if (s_registered && instance == 1) return s_kbd_report_desc;")
print("      return __real_tud_hid_descriptor_report_cb(instance);")
print()
print("  instance 0 -> Arduino 拼接描述符(鼠标+键盘), 长度 = 框架登记的长度")
print("  instance 1 -> 我的纯键盘描述符, 长度 = sizeof(s_kbd_report_desc)")
print()
print("  ✓ 两者长度各自与描述符里声明的 wReportLength 一致")
print()
print("-" * 72)
print("端点分配")
print("-" * 72)
print()
print("  第1轮 (HID, 在描述符回调里): get_free_in_endpoint()  -> ep_in")
print("                               get_free_out_endpoint() -> ep_out")
print("  第2轮 (我的回调):            get_free_in_endpoint()  -> 另一个 ep_in")
print()
print("  ★ 顺序问题: 描述符回调是在 USB.begin() 时执行的。")
print("    我的 dualHidLoadDescriptor 在第2轮才执行 -> 那时第1轮的端点已占用")
print("    -> 不会冲突 ✓")
